INSERT INTO GENDERS(NAME) VALUES('Accion');
INSERT INTO GENDERS(NAME) VALUES('Ficcion');
INSERT INTO GENDERS(NAME) VALUES('Drama');
INSERT INTO GENDERS(NAME) VALUES('Comedia');
INSERT INTO GENDERS(NAME) VALUES('Terror');

INSERT INTO ACTORS(NAME, IMAGE_URL) VALUES('Hugh Jackman', 'https://cdn.pixabay.com/photo/2019/06/22/20/55/godfather-4292451_1280.jpg');
INSERT INTO ACTORS(NAME, IMAGE_URL) VALUES('Keanu Reeves', 'https://cdn.pixabay.com/photo/2019/06/22/20/55/godfather-4292451_1280.jpg');
